FROM python:3.7

RUN apt-get update
RUN apt-get -y install python3-pip

RUN python3 -m pip install --upgrade pip

RUN pip install pipenv

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 80

ENTRYPOINT [ "python" ]

CMD ["app.py"]

